### ISSUE TITLE
How to update container environment variables

### ISSUE THREAD

**Issue by MarkPolivchuk** [awslabs/ecs-refarch-continuous-deployment#34]
I'm switching my application's deployment to CodePipeline and the ECS. Is there a way using this API to update the container's environment variables? Previously I was using the CLI to register the task definition as follows: 

```
export ENVIRONMENT=$(<environment.json)
aws ecs register-task-definition --family <family_name> --task-role-arn <iam_role> --container-definitions "$ENVIRONMENT"
aws ecs update-service --cluster <cluster_name> --service <service_name> --task-definition <family_name> --region us-west-2
```
And whatever variables were set in `environment.json` would be loaded into the container. I can't find any documentation describing how to set this using CloudFormation. Any ideas?

**Comment by jpignata** [comment]
Hi! The native CodePipeline -> ECS integration will only update the container definitions' `image` attribute so you cannot use it to manage environment variables. Luckily, you have a couple of other options:

- You can use a Lambda function instead to drive your deployment and do something similar to the above to edit both the `image` and `environment` attributes.
- If you're using CloudFormation to manage your task definition and service, you can use these templates to manage those fields instead of the native integration. See [the documentation][docs] for more details and a [previous iteration][previous] of this refarch for an example.

Hope that helps!

[docs]: https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/continuous-delivery-codepipeline.html
[previous]: https://github.com/awslabs/ecs-refarch-continuous-deployment/tree/a03ca6eba38838739b0863fa47bac35767e14115

**Comment by MarkPolivchuk** [comment]
Thank you for the quick response!
